name             'apache'
maintainer       'Iliya Strakovich'
maintainer_email 'iliya@strakovich.com'
license          'All rights reserved'
description      'Installs/Configures apache'
long_description 'Installs/Configures apache'
version          '0.4.1'
